project:
  type: website

website:
  title: "Victor Castro"
  navbar:
    right:
      - text: Research
        href: research.qmd
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/vcastro

format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual

